### ISSUE TITLE
Can you support the code page 936 ?

### ISSUE THREAD

**Issue by HopeLi90** [bonega/yore#2]
There are some chinese char or chinese string text , yore  can't  encode  these text, please add the code page of  CP936 to yore,thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bonega** [comment]
Hey,
Can you give a reference to the specification?
I think there is at least two different for CP936

**Comment by bonega** [comment]
Closing this one as inactive
