### ISSUE TITLE
Support for code page 910

### ISSUE THREAD

**Issue by EnderShadow** [bonega/yore#3]
Having support for code page 910 would be useful for a project I'm working on.

**Comment by bonega** [comment]
Any chance you could provide me an specification in this format: [CP857](https://github.com/bonega/yore/blob/master/codegen/tables/unicode.org/CP857.txt)
The second column is everything you need to change.

**Comment by EnderShadow** [comment]
Sure, do you want me to make a PR to put it with the other encodings?

**Comment by bonega** [comment]
Please do that
